Ft login using email and password 187300098
atlp-rwanda/alpha-ec-fe pull request #14
Opened 2024-06-02 21:52 UTC by IRASUBIZA-Elyse

### issue in referencing?

### Questions:

#### What does this PR do?

login using email and password

#### Description of Task to be completed?

-registered use use the email and the password to login

#### Any background context you want to provide?

-user should first register

#### What are the relevant pivotal tracker/Trello stories?

- id of the project
    #187300098

#### Questions:

2024-06-03 10:32 UTC, musabehonore approved these changes

2024-06-03 11:24 UTC, Sophie20202 approved these changes

2024-06-03 14:12 UTC, fab-ryan commented on src/app/(Authentication)/login/page.tsx
> +                </span>
regix for password doesn't required here

2024-06-03 14:18 UTC, fab-ryan requested changes
correct that file of validation

2024-06-04 09:01 UTC, TuyishimireEric approved these changes

2024-06-05 08:45 UTC, fab-ryan approved these changes

2024-06-05 08:46 UTC, merged