Ft login with google 187300097
atlp-rwanda/alpha-ec-fe pull request #15
Opened 2024-06-04 06:55 UTC by RWEMAREMY

### issue in referencing?

### Questions:

#### What does this PR do?

login using Google

#### Description of Task to be completed?

-A user should use the Google account to login

#### Any background context you want to provide?

-run "npm run dev" to try it out

#### What are the relevant pivotal tracker/Trello stories?

- id of the project
    #187300097

2024-06-11 08:56 UTC, fab-ryan commented on src/app/page.tsx
> +      console.log(token);
remove this console

2024-06-11 08:57 UTC, fab-ryan commented on src/services/authenticate/login.ts
> +  }
we don't have this file

2024-06-11 08:57 UTC, fab-ryan commented on src/services/authenticate/register.ts
> +  }
the same as this meaning you didn't rebase

2024-06-11 08:58 UTC, fab-ryan requested changes
rebase to the current branch develop

2024-06-13 13:39 UTC, fab-ryan commented on src/services/authenticate/login.ts
remove this file please

2024-06-13 13:39 UTC, fab-ryan commented on src/services/authenticate/register.ts
same as this

2024-06-13 13:39 UTC, fab-ryan requested changes
remove those files

2024-06-13 13:57 UTC, fab-ryan approved these changes

2024-06-13 14:03 UTC, Sophie20202 approved these changes

2024-06-13 14:04 UTC, musabehonore approved these changes

2024-06-13 14:10 UTC, Ruthuwamahoro approved these changes

2024-06-13 14:42 UTC, merged