#[187300100] [Seller auth & Two Factor Authentication for Sellers]
atlp-rwanda/alpha-ec-fe pull request #18
Opened 2024-06-05 14:52 UTC by Nadinefiona

#### What does this PR do?

Implement Seller Auth & Two-Factor Authentication for Sellers

#### Description of Task to be completed?

This pull request introduces a two-factor authentication (2FA) feature specifically for sellers on our platform.

#### How should this be manually tested?

npm run dev 
and then do login and make sure that you are seller just to verify OTP.

#### What are the relevant pivotal tracker/Trello stories?

#187300100

#### Screenshots (if appropriate)

2024-06-09 07:53 UTC, fab-ryan commented on .env
> +NEXT_PUBLIC_API_URL=https://alpha-ec-be-8i4x.onrender.com
remove this file

2024-06-09 07:55 UTC, fab-ryan commented on src/app/(Authentication)/sellerAuth/page.tsx
> +    if (verifyOtp.fulfilled.match(result)) {
make this a state in redux

2024-06-09 07:56 UTC, fab-ryan commented on src/redux/slices/otpSlice.ts
> +      })
use this states in tsx file

2024-06-09 07:56 UTC, fab-ryan requested changes
Work on those changes

2024-06-09 17:11 UTC, Nadinefiona commented
done

2024-06-10 11:04 UTC, fab-ryan approved these changes

2024-06-10 11:57 UTC, Ruthuwamahoro approved these changes

2024-06-10 12:05 UTC, merged