Ft admin view users assign roles #187300107
atlp-rwanda/alpha-ec-fe pull request #23
Opened 2024-06-13 15:19 UTC by manzidavidrw

#### What does this PR do?

Admin can view all registered Users 
Admin can assign roles to users 

#### Description of Task to be completed?

- Admin would be able to see the list of all registered Users
- Admin would be able to assign roles to the Users

#### How should this be manually tested?

- you should login first with Admin credentials to be able to perform any of these tasks

#### What are the relevant pivotal tracker/Trello stories?

- id of the project
#187300107

#### Questions:

2024-06-19 14:29 UTC, Ruthuwamahoro approved these changes

2024-06-20 09:55 UTC, fab-ryan commented on src/app/(Authentication)/login/page.tsx
> +          router.push('/dashboard');
you changed how login should worker

2024-06-20 10:03 UTC, fab-ryan commented on src/app/assignrole/page.tsx
> +  const dispatch = useAppDispatch();
we have already defined this dispatch which means you will get your function from dispatch

2024-06-20 10:04 UTC, fab-ryan commented on src/app/assignrole/page.tsx
> +    if (assignRole.fulfilled.match(result)) {
and again use states from redux not here

2024-06-20 10:04 UTC, fab-ryan commented on src/app/dashboard/page.tsx
> +
and again here

2024-06-20 10:04 UTC, fab-ryan commented on src/app/dashboard/page.tsx
> +
remember to remove console.log

2024-06-20 10:13 UTC, fab-ryan commented on src/redux/slices/assignroleSlice.ts
> +          : 'Unknown error';
why can't you use this states

2024-06-20 10:14 UTC, fab-ryan requested changes
test every each corner of your task

2024-06-23 22:10 UTC, fab-ryan approved these changes

2024-06-24 07:56 UTC, RWEMAREMY approved these changes
great work

2024-06-24 08:16 UTC, Mukunzijames approved these changes

2024-06-25 14:38 UTC, merged