feat(publicChat):user should be able to chat
atlp-rwanda/alpha-ec-fe pull request #32
Opened 2024-06-27 14:48 UTC by Mukunzijames

What does this PR do?

user should be able to chat in public chat

Description of Task to be completed?

user should be able to chat live we used socket.io firstly you have to login before being able to chat

What are the relevant pivotal tracker/Trello stories?

id of the project

[#187300111]

Questions:

2024-06-28 08:03 UTC, RWEMAREMY approved these changes
good

2024-06-28 13:50 UTC, musabehonore approved these changes

2024-06-29 20:39 UTC, fab-ryan commented on src/app/chat/page.tsx
> +    socket.current = io(process.env.NEXT_PUBLIC_API_URL as string, {
setup of io must not  be included here

2024-06-29 20:39 UTC, fab-ryan commented on src/app/chat/page.tsx
> +    });
please use the previous hooks created

2024-06-29 20:46 UTC, fab-ryan commented on src/app/chat/page.tsx
> +    };
use callbacck Hooks

2024-06-29 20:46 UTC, fab-ryan commented on src/app/chat/page.tsx
> +    };
insteady of useEffect Learn the different between useCallback and useEffect

2024-06-29 20:47 UTC, fab-ryan commented on src/app/layout.tsx
> +              {/* <Footer /> */}
Why did you disable this footer

2024-06-29 20:48 UTC, fab-ryan commented on src/components/Card.tsx
> +  const isSelf = senderId === localStorage.getItem('userId');
create helper that checks userId not Here also userId may be undefined this means I can get error

2024-06-29 20:48 UTC, fab-ryan commented on src/components/ChatForm.tsx
> +    dispatch(fetchProfile());
same as here Please use hooks for dispatch

2024-06-29 20:49 UTC, fab-ryan commented on src/components/ChatForm.tsx
> +          }}
create this as separate function

2024-06-29 20:49 UTC, fab-ryan commented on src/components/ChatList.tsx
> +          isSelf={message.senderId === localStorage.getItem('userId')}
same as here that function are required

2024-06-29 20:50 UTC, fab-ryan commented on src/components/Footer/Footer.tsx
> +//       </nav>
why the whole footer is commented

2024-06-29 20:50 UTC, fab-ryan commented on src/redux/slices/chatSlice.ts
> +      state.loading = action.payload;
Loading states is not being used in pages

2024-06-29 20:51 UTC, fab-ryan commented on src/utils/requests.ts
> +// );
Guys why changing someone else codes??

2024-06-29 20:52 UTC, fab-ryan requested changes
Work on those comments you have repetitive implementation in whole pages.
also don't touch someone else's task

2024-07-01 08:26 UTC, fab-ryan approved these changes

2024-07-01 08:26 UTC, merged