hound CI and eslint configuration ##187300093
atlp-rwanda/alpha-ec-fe pull request #4
Opened 2024-05-24 09:29 UTC by manzidavidrw

#### What does this PR do?

configure Hound CI and eslint

#### Description of Task to be completed?

- Configure The App to follow  rules
- Configure Hound to track issues

#### How should this be manually tested?

- to run lint use "npm run lint "
- Hound CI automatically runs it self whenever you push

#### Any background context you want to provide?

-this is for specifically allow order of codebase 

#### What are the relevant pivotal tracker/Trello stories?

- id of the project
  #187300093

2024-05-24 09:43 UTC, fab-ryan requested changes
Hound not configured add it also

2024-05-24 09:59 UTC, manzidavidrw commented
> Hound not configured add it also

hound check passed

2024-05-24 12:17 UTC, Mukunzijames approved these changes
Where is  eslint  configuration

2024-05-24 14:12 UTC, fab-ryan commented on .eslintrc.json
> +    "react/jsx-filename-extension": [1, { "extensions": [".js", ".jsx"] }],
extension add tsx

2024-05-24 14:12 UTC, fab-ryan commented on .eslintrc.json
> +      }
here also

2024-05-24 14:13 UTC, fab-ryan requested changes
Change that

2024-05-24 15:06 UTC, Mukunzijames approved these changes

2024-05-24 19:06 UTC, fab-ryan requested changes
Please change target branch to be develop not main

2024-05-24 21:07 UTC, manzidavidrw commented
> Please change target branch to be develop not main

Done

2024-05-26 06:41 UTC, fab-ryan approved these changes

2024-05-26 13:27 UTC, Nadinefiona approved these changes

2024-05-26 15:27 UTC, merged