fx(sidebar)
atlp-rwanda/alpha-ec-fe pull request #40
Opened 2024-07-08 09:34 UTC by Nadinefiona

#### What does this PR do?

This PR fix some issues that was on sidebars and logout functionality

#### Description of Task to be completed?

this task is fix of sidebar and logout functionality where logged in user can click on button of logout and redirects to login, where token will become expired.

#### How should this be manually tested?

login for any user and click on button of logout

2024-07-08 14:26 UTC, fab-ryan commented on src/utils/logout.ts
> +      } else {
Please use  redux

2024-07-08 14:26 UTC, fab-ryan requested changes
Please correct that implementation meaning I need only redux to be used

2024-07-09 11:36 UTC, fab-ryan approved these changes

2024-07-09 12:00 UTC, musabehonore approved these changes

2024-07-09 12:44 UTC, Ruthuwamahoro approved these changes

2024-07-09 12:49 UTC, RWEMAREMY approved these changes
Great job

2024-07-09 13:16 UTC, merged