Ft vieworder updateorder status 187300125
atlp-rwanda/alpha-ec-fe pull request #41
Opened 2024-07-08 13:14 UTC by RWEMAREMY

##What does this PR do?
the seller can update status and view orders

#Description of Task to be completed?
-navigate to order as the card is hit the pop up displays
- choose the status
-confirm on update.
What are the relevant pivotal tracker/Trello stories?
[Delivered #187300125]

2024-07-08 15:20 UTC, fab-ryan commented on src/components/order/orderCard.tsx
> +      });
redux, redux

2024-07-08 15:21 UTC, fab-ryan requested changes
Please use redux in updating order status

2024-07-09 05:08 UTC, Mukunzijames approved these changes
resolve conflict

2024-07-11 22:32 UTC, fab-ryan approved these changes

2024-07-12 07:33 UTC, musabehonore approved these changes

2024-07-12 07:34 UTC, merged