feat(redux):setUp[#187300086]
atlp-rwanda/alpha-ec-fe pull request #5
Opened 2024-05-26 04:43 UTC by Mukunzijames

What does this PR do?
configure redux toolkit for next js14

Description of Task to be completed?

Configure The App to follow rules

Configure redux toolkit and slices 

How should this be manually tested?

to run dev use "npm run dev "

redux toolkit automatically runs it self whenever you push

Any background context you want to provide?
-this is for specifically allow order of codebase

What are the relevant pivotal tracker/Trello stories?

id of the project

#187300086

2024-05-26 05:44 UTC, musabehonore approved these changes

2024-05-26 07:29 UTC, fab-ryan requested changes
any type are not allowed,
create custom hook for getting typed actions and typed slice

2024-05-26 09:23 UTC, Mukunzijames commented
> any type are not allowed, create custom hook for getting typed actions and typed slice

solved

2024-05-26 09:44 UTC, IRASUBIZA-Elyse approved these changes

2024-05-26 13:27 UTC, Nadinefiona approved these changes

2024-05-26 15:49 UTC, fab-ryan requested changes
make the following structure folder for hooks
- slices folders not actionType folder should be there

2024-05-26 16:15 UTC, fab-ryan commented on src/redux/provider.tsx
> +export default Providers;
new line here

2024-05-26 16:18 UTC, fab-ryan commented on src/redux/slices/postSlice.ts
> +
where is that function

2024-05-26 16:18 UTC, fab-ryan requested changes
you have removed the previous

2024-05-26 18:04 UTC, fab-ryan commented on src/redux/slices/postThunk.ts
don't create separate function please

2024-05-26 18:04 UTC, fab-ryan commented on src/redux/slices/postSlice.ts
> +
add it here

2024-05-26 18:04 UTC, fab-ryan requested changes
Please follow my requests

2024-05-27 07:33 UTC, fab-ryan approved these changes

2024-05-27 07:33 UTC, merged