[#187300092] [Set up Local tests & CI]
atlp-rwanda/alpha-ec-fe pull request #6
Opened 2024-05-26 14:07 UTC by Nadinefiona

## What does this PR do?

This PR sets up local tests and integrates all necessary Continuous Integration (CI) tools, including CodeClimate and CircleCI. It also adds badges to the README file.

## Description of Task to be completed?

The primary task accomplished in this PR is to establish a robust testing framework locally and integrate it with our CI pipeline. 

## How should this be manually tested?

this will be tested by running "npm run test "

## What are the relevant pivotal tracker/Trello stories?

- Trello ID: [#187300092]

2024-05-26 15:34 UTC, fab-ryan commented on package.json
> +    "mocha": "^10.4.0",
we use Jest for testing

2024-05-26 15:34 UTC, fab-ryan commented on package.json
> +    "mocha": "^10.4.0",
we use Jest for testing

2024-05-26 15:35 UTC, fab-ryan requested changes
You will use Jest testing not chai

2024-05-26 18:06 UTC, fab-ryan requested changes
add Single one test

2024-05-27 07:32 UTC, fab-ryan requested changes
add one test

2024-05-27 09:18 UTC, Nadinefiona commented
> add one test



> add one test
sure,I am working on it.

2024-05-27 13:14 UTC, fab-ryan approved these changes

2024-05-29 11:08 UTC, musabehonore approved these changes

2024-05-29 11:09 UTC, Sophie20202 approved these changes

2024-05-29 11:40 UTC, RWEMAREMY approved these changes
good job

2024-05-29 12:02 UTC, merged