chore(Tailwind):setup[#187300090]
atlp-rwanda/alpha-ec-fe pull request #7
Opened 2024-05-26 15:26 UTC by RWEMAREMY

#### What does this PR do?

Setting up Tailwind

#### Description of Task to be completed?

-setting css framework to easy styling
 
#### How should this be manually tested?

- to run tailwind use "npm run build-css "

#### What are the relevant pivotal tracker/Trello stories?

- id of the project
  #187300090

2024-05-26 15:31 UTC, fab-ryan commented on dist/input.css
remove this dist folder

2024-05-26 15:31 UTC, fab-ryan commented on tailwind.config.ts
> +      },
why did you add only dark mode only

2024-05-26 15:32 UTC, fab-ryan requested changes
the setup not complete

2024-05-26 15:37 UTC, Mukunzijames approved these changes

2024-05-26 15:39 UTC, RWEMAREMY commented on dist/input.css
my bad , with that said it's done!!!

2024-05-26 18:07 UTC, fab-ryan reviewed
Please if there is no dark mode then set up the colors right

2024-05-27 20:15 UTC, fab-ryan commented on tailwind.config.ts
> +      },
no this is not what I mean I mean themes like if it;s blue, light blue, text colors

2024-05-27 20:15 UTC, fab-ryan requested changes
Correct that themes

2024-05-28 09:15 UTC, Ruthuwamahoro approved these changes

2024-05-28 11:59 UTC, fab-ryan approved these changes
Correct that themes

2024-05-28 11:59 UTC, merged