Ch storybook configuration #187300095
atlp-rwanda/alpha-ec-fe pull request #8
Opened 2024-05-26 16:19 UTC by Sophie20202

**What does this PR do?**
 Storybook  Configuration

**Description of Task to be completed?**
Configure the storybook tool to make the working on related components more efficient, easier to reuse and have better component documentation.

**How should this be manually tested?**
to run storytbook use "npm run storytbook "
**What are the relevant pivotal tracker/Trello stories?**
id of the project
#187300095

2024-05-26 21:23 UTC, fab-ryan requested changes
why do we have those assets here 
- remove this configure.mdx
- put builded folder of story book in gitignore

2024-05-27 13:10 UTC, fab-ryan requested changes
Good worker

2024-05-27 13:11 UTC, fab-ryan approved these changes

2024-05-27 13:26 UTC, Nadinefiona approved these changes

2024-05-27 13:33 UTC, musabehonore approved these changes

2024-05-27 13:39 UTC, Ruthuwamahoro approved these changes

2024-05-27 13:56 UTC, merged